Models/MainTbl.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

// Code scaffolded by EF Core assumes nullable reference types (NRTs) are not used or disabled.
// If you have enabled NRTs for your project, then un-comment the following line:
// #nullable disable

namespace FeGv3.Models
{
    public partial class MainTbl
    {
        public MainTbl()
        {
            Biology = new HashSet<Biology>();
            Bones = new HashSet<Bones>();
            Samples = new HashSet<Samples>();
        }
        [Key]
        public double BurialId { get; set; }
        public string BurialLocationNs { get; set; }
        public string BurialLocationEw { get; set; }
        public double? LowPairNs { get; set; }
        public double? HighPairNs { get; set; }
        public double? LowPairEw { get; set; }
        public double? HighPairEw { get; set; }
        public string BurialSubplot { get; set; }
        public string Area { get; set; }
        public double? BurialDepth { get; set; }
        public double? SouthToHead { get; set; }
        public double? SouthToFeet { get; set; }
        public double? WestToHead { get; set; }
        public double? WestToFeet { get; set; }
        public string BurialSituation { get; set; }
        public double? LengthOfRemains { get; set; }
        public double? BurialNumber { get; set; }
        public double? SampleNumber { get; set; }
        public string GenderGe { get; set; }
        public string Burialgendermethod { get; set; }
        public string AgeCodeSingle { get; set; }
        public double? GeFunctionTotal { get; set; }
        public string GenderBodyCol { get; set; }
        public string ArtifactsDescription { get; set; }
        public string HairColor { get; set; }
        public string HairColorCode { get; set; }
        public string PreservationIndex { get; set; }
        public string YearFound { get; set; }
        public string MonthFound { get; set; }
        public string DayFound { get; set; }
        public string DateFound { get; set; }
        public string HeadDirection { get; set; }
        public string Burialageatdeath { get; set; }
        public string Burialagemethod { get; set; }
        public string YearOnSkull { get; set; }
        public string MonthOnSkull { get; set; }
        public string DateOnSkull { get; set; }
        public string FieldBook { get; set; }
        public string FieldBookPageNumber { get; set; }
        public string InitialsOfDataEntryExpert { get; set; }
        public string InitialsOfDataEntryChecker { get; set; }
        public string ByuSample { get; set; }
        public string BodyAnalysis { get; set; }
        public string SkullAtMagazine { get; set; }
        public string PostcraniaAtMagazine { get; set; }
        public string SexSkull2018 { get; set; }
        public string AgeSkull2018 { get; set; }
        public string RackAndShelf { get; set; }
        public string ToBeConfirmed { get; set; }
        public string SkullTrauma { get; set; }
        public string PostcraniaTrauma { get; set; }
        public string CribraOrbitala { get; set; }
        public string PoroticHyperostosis { get; set; }
        public string PoroticHyperostosisLocations { get; set; }
        public string MetopicSuture { get; set; }
        public string ButtonOsteoma { get; set; }
        public string PostcraniaTrauma1 { get; set; }
        public string OsteologyUnknownComment { get; set; }
        public string TemporalMandibularJointOsteoarthritisTmjOa { get; set; }
        public string LinearHypoplasiaEnamel { get; set; }
        public string BurialWrapping { get; set; }
        public string BurialAdultChild { get; set; }
        public string Goods { get; set; }
        public string Cluster { get; set; }
        public string FaceBundle { get; set; }
        public bool Photos { get; set; } //are there photos in the dataset (Y or N)

        public virtual ICollection<Biology> Biology { get; set; }
        public virtual ICollection<Bones> Bones { get; set; }
        public virtual ICollection<Samples> Samples { get; set; }
    }
}

Components/FilterViewComponent.cs
using FeGv3.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace FeGv3.Components
{
    public class FilterViewComponent : ViewComponent
    {
        private FagElGamousContext context;

        //constructor
        public FilterViewComponent(FagElGamousContext ctx)
        {
            context = ctx;
        }

        public IViewComponentResult Invoke()
        {
            return View(context.MainTbl
                //.Select(x => x.)
                .Distinct()
                .OrderBy(x => x)
                .ToList());
        }
    }
}

Controllers/MainTblsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using FeGv3.Models;
using FeGv3.Models.ViewModels;
using Microsoft.AspNetCore.Authorization;

namespace FeGv3.Controllers
{
    public class MainTblsController : Controller
    {
        private FagElGamousContext _context { get; set; }
        public int pageSize = 20;

        public MainTblsController(FagElGamousContext context)
        {
            _context = context;
        }
        //public IActionResult Index(int pageNum = 1)
        //{
        //    //return View(await _context.MainTbl.ToListAsync());

        //    int pageSize = 20;

        //    return View(new IndexViewModel
        //    {
        //        MainTbls = (_context.MainTbl
        //        .OrderBy(m => m.BurialId)
        //            .Skip((pageNum - 1) * pageSize)
        //            .Take(pageSize)),


        //        PaginationModel = new PaginationModel
        //        {
        //            ItemsPerPage = pageSize,
        //            CurrPage = pageNum,

        //            TotalItems = _context.MainTbl.Count()
        //        },
        //    });


        //}

        // GET: MainTbls
        [HttpGet]        
        public IActionResult Index(string option, string search, int pageNum = 1)
        {            
            if (System.String.IsNullOrEmpty(option) && System.String.IsNullOrEmpty(search))
            {
                return View(new IndexViewModel
                {
                    MainTbls = (_context.MainTbl
                        .OrderBy(m => m.BurialId)
                        .Skip((pageNum - 1) * pageSize)
                        .Take(pageSize)),
                    PaginationModel = new PaginationModel
                    {
                        ItemsPerPage = pageSize,
                        CurrPage = pageNum,
                        TotalItems = _context.MainTbl.Count()                        
                    },
                    Search = search,
                    Option = option
                });
            }            
            else
            {
                if (option == "LowNS")
                {
                    return View(new IndexViewModel
                    {
                        MainTbls = _context.MainTbl
                            .Where(x => x.LowPairNs.ToString() == search || search == null)
                            .OrderBy(m => m.BurialId)
                            .Skip((pageNum - 1) * pageSize)
                            .Take(pageSize)
                            .ToList(),
                        PaginationModel = new PaginationModel
                        {
                            ItemsPerPage = pageSize,
                            CurrPage = pageNum,
                            TotalItems = _context.MainTbl
                                .Where(x => x.LowPairNs.ToString() == search || search == null)
                                .Count()
                        },
                        Search = search,
                        Option = option
                    });                                        
                }
                else if (option == "LowEW")
                {
                    return View(new IndexViewModel
                    {
                        MainTbls = _context.MainTbl
                            .Where(x => x.LowPairEw.ToString() == search || search == null)
                            .OrderBy(m => m.BurialId)
                            .Skip((pageNum - 1) * pageSize)
                            .Take(pageSize)
                            .ToList(),
                        PaginationModel = new PaginationModel
                        {
                            ItemsPerPage = pageSize,
                            CurrPage = pageNum,
                            TotalItems = _context.MainTbl
                                .Where(x => x.LowPairEw.ToString() == search || search == null)
                                .Count()
                        },
                        Search = search,
                        Option = option
                    });
                }
                else if (option == "BurialNumber")
                {
                    return View(new IndexViewModel
                    {
                        MainTbls = _context.MainTbl
                            .Where(x => x.BurialNumber.ToString() == search || search == null)
                            .OrderBy(m => m.BurialId)
                            .Skip((pageNum - 1) * pageSize)
                            .Take(pageSize)
                            .ToList(),
                        PaginationModel = new PaginationModel
                        {
                            ItemsPerPage = pageSize,
                            CurrPage = pageNum,
                            TotalItems = _context.MainTbl
                                .Where(x => x.BurialNumber.ToString() == search || search == null)
                                .Count()
                        },
                        Search = search,
                        Option = option
                    });
                }
                //else if (option == "Gender")
                //{
                //    return View(new IndexViewModel
                //    {
                //        MainTbls = _context.MainTbl
                //            .Where(x => x.GenderGe == search)
                //            .OrderBy(m => m.BurialId)
                //            .Skip((pageNum - 1) * pageSize)
                //            .Take(pageSize)
                //            .ToList(),
                //        PaginationModel = new PaginationModel
                //        {
                //            ItemsPerPage = pageSize,
                //            CurrPage = pageNum,
                //            TotalItems = _context.MainTbl
                //                .Where(x => x.GenderGe == search || search == null)
                //                .Count()
                //        }
                //    });
                //}
                else
                {
                    return View(new IndexViewModel
                    {
                        MainTbls = (_context.MainTbl
                        .OrderBy(m => m.BurialId)
                        .Skip((pageNum - 1) * pageSize)
                        .Take(pageSize)),
                        PaginationModel = new PaginationModel
                        {
                            ItemsPerPage = pageSize,
                            CurrPage = pageNum,
                            TotalItems = _context.MainTbl.Count()
                        },
                        Search = search,
                        Option = option
                    });
                }
            }            
        }

        // GET: MainTbls/Details/5
        /*
        public async Task<IActionResult> Details(double? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var burialDetails = await _context.MainTbl
                .FirstOrDefaultAsync(m => m.BurialId == id);
            if (burialDetails == null)
            {
                return NotFound();
            }

            return View(burialDetails);
        }
        */
        //GET: MainTbls/Create
        [Authorize(Roles = "Admin, Researcher")]
        public IActionResult Create()   // you'll need to pass in the role of the user here
        {
            //if (_context.UserInfo.Where(x => x.role == role) == null)
            //{
            //    return NotFound(); //we want to return not found, but also not show the View if they aren't a researcher (so you'll need to edit the view too)
            //};
            return View();
        }

        // POST: MainTbls/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        [Authorize(Roles = "Admin, Researcher")]
        public async Task<IActionResult> Create([Bind("BurialId,BurialLocationNs,BurialLocationEw,LowPairNs,HighPairNs,LowPairEw,HighPairEw,BurialSubplot,Area,BurialDepth,SouthToHead,SouthToFeet,WestToHead,WestToFeet,BurialSituation,LengthOfRemains,BurialNumber,SampleNumber,GenderGe,Burialgendermethod,AgeCodeSingle,GeFunctionTotal,GenderBodyCol,ArtifactsDescription,HairColor,HairColorCode,PreservationIndex,YearFound,MonthFound,DayFound,DateFound,HeadDirection,Burialageatdeath,Burialagemethod,YearOnSkull,MonthOnSkull,DateOnSkull,FieldBook,FieldBookPageNumber,InitialsOfDataEntryExpert,InitialsOfDataEntryChecker,ByuSample,BodyAnalysis,SkullAtMagazine,PostcraniaAtMagazine,SexSkull2018,AgeSkull2018,RackAndShelf,ToBeConfirmed,SkullTrauma,PostcraniaTrauma,CribraOrbitala,PoroticHyperostosis,PoroticHyperostosisLocations,MetopicSuture,ButtonOsteoma,PostcraniaTrauma1,OsteologyUnknownComment,TemporalMandibularJointOsteoarthritisTmjOa,LinearHypoplasiaEnamel,BurialWrapping,BurialAdultChild,Goods,Cluster,FaceBundle")] MainTbl mainTbl)
        {
            if (ModelState.IsValid)
            {
                // mainTbl.BurialId = _context.MainTbl.Count() + 1;

                _context.Add(mainTbl);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(mainTbl);
        }

        // GET: MainTbls/Edit/5
        [Authorize(Roles = "Admin, Researcher")]
        public async Task<IActionResult> Edit(double? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var mainTbl = await _context.MainTbl.FindAsync(id);

Views/MainTbls/Index.cshtml
@model IndexViewModel

@{
    ViewData["Title"] = "Index";
}

<div class="row">
    <div class="text-left col-6">
        <h1>Mummies</h1>
    </div>       

    <div class="form-group text-right col-6">
        <form asp-action="Index" asp-controller="MainTbls" method="get">
            <label for="option">Search by:</label>
            <select name="option" id="option">
                <option value="Select">Select One</option>
                <option value="LowNS">Low NS Location</option>
                <option value="LowEW">Low EW Location</option>
                <option value="BurialNumber">Burial Number</option>
                @*<option value="Gender">Gender</option>*@
            </select>

            <input class="form-control" type="text" placeholder="Search" name="search" id="search">
            <button class="btn btn-primary" name="submit" type="submit">Search</button>
        </form>
    </div>
</div>

<p>
    <a asp-action="Create">Create New</a>
</p>

@*Want it to look like this:
  N 190/200 E 40/50 SE #9*@
<div class="row">
    <div class="col-2">
        <vc:filter />
    </div>

    <div class="col-10">
        <table class="table">
            <thead>
                <tr>
                    <th>
                        Location/Burial#
                    </th>
                    <th>
                        Burial Depth
                    </th>
                    <th>
                        Burial Situation
                    </th>
                    <th>
                        Length of Remains
                    </th>
                    <th>
                        Gender GE
                    </th>
                    <th>
                        Year Found
                    </th>
                    <th>
                        Head Direction
                    </th>
                    <th></th>
                </tr>
            </thead>

            @*Want it to look like this:
            N 190/200 E 40/50 SE #9*@

            <tbody>
                @foreach (var item in Model.MainTbls)
                {
                    <tr>
                        <td>
                            @Html.DisplayFor(modelItem => item.BurialLocationNs) @Html.DisplayFor(modelItem => item.LowPairNs)/@Html.DisplayFor(modelItem => item.HighPairNs)
                            @Html.DisplayFor(modelItem => item.BurialLocationEw) @Html.DisplayFor(modelItem => item.LowPairEw)/@Html.DisplayFor(modelItem => item.HighPairEw)
                            @Html.DisplayFor(modelItem => item.BurialSubplot) #@Html.DisplayFor(modelItem => item.BurialNumber)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BurialDepth)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.BurialSituation)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.LengthOfRemains)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.GenderGe)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.YearFound)
                        </td>
                        <td>
                            @Html.DisplayFor(modelItem => item.HeadDirection)
                        </td>
                        <td>
                            @if (User.IsInRole("Researcher") || User.IsInRole("Admin"))
                            {
                                <a asp-action="Edit" asp-route-id="@item.BurialId">Edit</a>
                            }
                            <form asp-action="BurialDetails" asp-controller="Home" method="get">
                                <input hidden value="@item.BurialId" name="burialId" />
                                <input type="submit" value="Details" />
                            </form>
                            @if (User.IsInRole("Admin"))
                            {
                                <a asp-action="Delete" asp-route-id="@item.BurialId">Delete</a>
                            }
                        </td>
                    </tr>
                }
            </tbody>
        </table>
    </div>
</div>

<div page-info="@Model.PaginationModel" page-class-normal="btn btn-outline-primary mx-1" page-class-selected="btn btn-primary mx-1" 
     page-url-search="@Model.Search"
     page-url-option="@Model.Option">
</div>